SELECT  A.PRODUCT_ID
        ,A.PRODUCT_NAME
        ,SUM(A.PRICE * B.AMOUNT) AS TOTAL_SALES
  FROM  FOOD_PRODUCT AS A
  LEFT
  JOIN  FOOD_ORDER AS B
    ON  A.PRODUCT_ID = B.PRODUCT_ID
 WHERE  DATE_FORMAT(B.PRODUCE_DATE, '%Y-%m') = '2022-05'
 GROUP
    BY  A.PRODUCT_ID
 ORDER
    BY  SUM(A.PRICE * B.AMOUNT) DESC
        ,A.PRODUCT_ID ASC;