SELECT  DISTINCT B.ID
        ,B.EMAIL
        ,B.FIRST_NAME
        ,B.LAST_NAME
  FROM  SKILLCODES AS A
 RIGHT
  JOIN  DEVELOPERS AS B
    ON  A.CODE & B.SKILL_CODE
 WHERE  A.CATEGORY = 'Front End'
 ORDER
    BY  B.ID ASC;