-- 문제 이상함. 복습 제외.

WITH MAX_REVIEW AS (
    SELECT  A.MEMBER_ID
      FROM  MEMBER_PROFILE AS A
     RIGHT
      JOIN  REST_REVIEW AS B
        ON  A.MEMBER_ID = B.MEMBER_ID
     GROUP
        BY  A.MEMBER_ID
     ORDER
        BY  COUNT(*) DESC
    LIMIT 1)

SELECT  A.MEMBER_NAME
        ,B.REVIEW_TEXT
        ,DATE_FORMAT(B.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
  FROM  MEMBER_PROFILE AS A
 RIGHT
  JOIN  REST_REVIEW AS B
    ON  A.MEMBER_ID = B.MEMBER_ID
 INNER
  JOIN  MAX_REVIEW AS C
    ON  B.MEMBER_ID = C.MEMBER_ID
 ORDER
    BY  REVIEW_DATE ASC
        ,REVIEW_TEXT ASC;