-- 코드 실행은 통과, 제출 후 채점 시 실패
SELECT  C.ID
        ,C.GENOTYPE
        ,P.GENOTYPE AS PARENT_GENOTYPE
  FROM  ECOLI_DATA AS P
  LEFT
  JOIN  ECOLI_DATA AS C
    ON  P.ID = C.PARENT_ID
 WHERE  P.GENOTYPE & C.GENOTYPE = P.GENOTYPE
 ORDER
    BY  P.ID ASC;