WITH TRG_CAR
    AS (SELECT  CAR_ID
          FROM  CAR_RENTAL_COMPANY_RENTAL_HISTORY
         WHERE  DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
         GROUP
            BY  CAR_ID
        HAVING  COUNT(*) >= 5)

SELECT  MONTH(START_DATE)
        ,CAR_ID
        ,COUNT(*) AS RECOFDS
  FROM  CAR_RENTAL_COMPANY_RENTAL_HISTORY
 WHERE  DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
   AND  CAR_ID IN (SELECT  CAR_ID
                     FROM  TRG_CAR)
 GROUP
    BY  MONTH(START_DATE)
        ,CAR_ID
HAVING  COUNT(*) > 0
 ORDER
    BY  MONTH(START_DATE) ASC
        ,CAR_ID DESC;