WITH CTE AS (
    SELECT  CATEGORY
            ,MAX(PRICE) AS MAX_PRICE
      FROM  FOOD_PRODUCT
     GROUP
        BY  CATEGORY
)

SELECT  A.CATEGORY
        ,B.MAX_PRICE
        ,A.PRODUCT_NAME
  FROM  FOOD_PRODUCT AS A
 INNER
  JOIN  CTE AS B
    ON  A.CATEGORY = B.CATEGORY
   AND  A.PRICE = B.MAX_PRICE
 GROUP
    BY  A.CATEGORY
HAVING  A.CATEGORY IN ('과자', '국', '김치', '식용유')
 ORDER
    BY  B.MAX_PRICE DESC;