WITH CTE AS
(
SELECT  FOOD_TYPE
        ,MAX(FAVORITES) AS MAX_FAVORITES
  FROM  REST_INFO
 GROUP
    BY  FOOD_TYPE
)
SELECT  A.FOOD_TYPE
        ,A.REST_ID
        ,A.REST_NAME
        ,A.FAVORITES
  FROM  REST_INFO AS A  
 INNER
  JOIN  CTE AS B
    ON  A.FOOD_TYPE = B.FOOD_TYPE
   AND  A.FAVORITES = B.MAX_FAVORITES
 ORDER
    BY  A.FOOD_TYPE DESC;