SELECT  ITEM_ID
        ,ITEM_NAME
        ,RARITY
  FROM  ITEM_INFO
 WHERE  NOT ITEM_ID IN (SELECT  PARENT_ITEM_ID
                          FROM  ITEM_TREE
                         WHERE  PARENT_ITEM_ID IS NOT NULL)
 ORDER
    BY  ITEM_ID DESC;