-- [SOL 1]
WITH RECURSIVE CTE AS (
  SELECT  20 AS N
  UNION ALL
  SELECT  N - 1
    FROM  CTE
   WHERE  N > 1
)
SELECT  REPEAT('* ', N)
  FROM  CTE;

-- [SOL 2]
SET @N = 21;
SELECT  REPEAT('* ', @N := @N - 1)
  FROM  INFORMATION_SCHEMA.TABLES
 WHERE  @N > 1;