/*
RIGHT JOIN으로도 동일한 출력값을 얻을 수 있지만 다음과 같은 문제가 있을 수 있으므로 INNER JOIN을 사용할 것.
COMPANY 테이블과 LEAD_MANAGER 테이블을 COMPANY_CODE를 기준으로 RIGHT JOIN했을 때
특정 회사 코드 값이 COMPANY.COMPANY_CODE에는 없으나, LEAD_MANGER.COMPANY_CODE에는 있을 경우 
GROUP BY COMPANY.COMPANY_CODE 수행 후 결과 출력 시
COMPANY.COMPANY_CODE 열에 NULL이 포함된 레코드가 생성됨.
*/

SELECT  A.COMPANY_CODE
        ,A.FOUNDER
        ,COUNT(DISTINCT B.LEAD_MANAGER_CODE)
        ,COUNT(DISTINCT C.SENIOR_MANAGER_CODE)
        ,COUNT(DISTINCT D.MANAGER_CODE)
        ,COUNT(DISTINCT E.EMPLOYEE_CODE)
  FROM  COMPANY AS A
 INNER
  JOIN  LEAD_MANAGER AS B
    ON  A.COMPANY_CODE = B.COMPANY_CODE
 INNER
  JOIN  SENIOR_MANAGER AS C
    ON  B.LEAD_MANAGER_CODE = C.LEAD_MANAGER_CODE
 INNER
  JOIN  MANAGER AS D
    ON  C.SENIOR_MANAGER_CODE = D.SENIOR_MANAGER_CODE
 INNER
  JOIN  EMPLOYEE AS E
    ON  D.MANAGER_CODE = E.MANAGER_CODE
 GROUP
    BY  A.COMPANY_CODE
        ,A.FOUNDER
 ORDER
    BY  A.COMPANY_CODE ASC;