SELECT  CASE WHEN B.GRADE < 8 THEN NULL
             ELSE A.NAME
             END
        ,B.GRADE
        ,A.MARKS
  FROM  STUDENTS AS A
 INNER
  JOIN  GRADES AS B
    ON  A.MARKS BETWEEN B.MIN_MARK AND B.MAX_MARK
 ORDER
    BY  B.GRADE DESC
        ,A.NAME ASC;